# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.Location')),
            ],
        ),
    ]
